# Generated by Django 3.2 on 2022-11-26 15:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('downloadview', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='media')),
                ('keyword', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.author')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('adress', models.CharField(max_length=500)),
                ('phon_number', models.CharField(max_length=13)),
                ('facs_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('top', models.BooleanField(default=False)),
                ('number_table', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.video')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('adress', models.CharField(max_length=500)),
                ('phon_number', models.CharField(max_length=13)),
                ('facs_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Statya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.author')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.jurnal')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('link', models.URLField()),
                ('phon_number', models.CharField(max_length=13)),
                ('date', models.DateField()),
                ('sponsor', models.CharField(max_length=250)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization')),
            ],
        ),
        migrations.AddField(
            model_name='jurnal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('adress', models.CharField(max_length=500)),
                ('phon_number', models.CharField(max_length=13)),
                ('date', models.DateField()),
                ('sponsor', models.CharField(max_length=250)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization')),
            ],
        ),
    ]
