# Generated by Django 3.2 on 2022-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statya',
            name='downloadfile',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statya',
            name='downloadview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statya',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
