# Generated by Django 3.2 on 2022-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0003_auto_20221130_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='issn',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
