# Generated by Django 3.2 on 2022-12-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0004_organization_issn'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
