# Generated by Django 3.2 on 2022-12-07 17:39
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0007_statya_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statya',
            name='keyword',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
