# Generated by Django 3.2 on 2022-12-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0008_auto_20221207_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statya',
            name='author',
        ),
    ]
