# Generated by Django 3.2 on 2022-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0009_remove_statya_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='author',
            field=models.ManyToManyField(to='pharmapolls.Author'),
        ),
    ]
