# Generated by Django 3.2 on 2022-12-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0010_statya_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='taklif',
            new_name='message',
        ),
        migrations.AddField(
            model_name='author',
            name='count_author',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='lavozim',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='theme',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
