# Generated by Django 4.1.4 on 2023-01-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0012_auto_20221220_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminar',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statya',
            name='author',
            field=models.ManyToManyField(related_name='article_author', to='pharmapolls.author'),
        ),
        migrations.AlterField(
            model_name='statya',
            name='jurnal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_article', to='pharmapolls.jurnal'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_subdivision', to='pharmapolls.organization'),
        ),
    ]
