# Generated by Django 4.1.4 on 2023-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0013_conference_archive_seminar_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number_table',
            field=models.IntegerField(unique=True),
        ),
    ]
