# Generated by Django 3.2 on 2023-01-17 16:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0015_banner_faq_webcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='adress_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='adress_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='adress_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
