# Generated by Django 4.1.5 on 2023-01-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0016_auto_20230117_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='adress_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='adress_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='adress_uz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_uz',
        ),
    ]
