# Generated by Django 4.1.5 on 2023-01-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0022_auto_20230120_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='author_uz',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_uz',
        ),
    ]
