# Generated by Django 3.2 on 2023-01-22 05:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0023_remove_jurnal_author_en_remove_jurnal_author_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.author'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.author'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='author_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.author'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='organization_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='organization_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='organization_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='adress_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='adress_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='adress_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='organization_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subdivision', to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='organization_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subdivision', to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='organization_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subdivision', to='pharmapolls.organization'),
        ),
    ]
