# Generated by Django 3.2 on 2023-01-22 07:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0025_auto_20230122_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='linkbutton_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='linkbutton_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='linkbutton_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='organization_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='organization_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='organization_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='sponsor_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='sponsor_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='sponsor_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
