# Generated by Django 3.2 on 2023-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0029_auto_20230122_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='address_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='address_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='address_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
