# Generated by Django 3.2 on 2023-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0030_auto_20230122_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='organization_uz',
        ),
        migrations.AddField(
            model_name='jurnal',
            name='keyword_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='keyword_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='keyword_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
